moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fake_arm_controller
    - fake_gripper_controller

  fake_arm_controller:
    type: "fake"
    joints:
      - joint_1
      - joint_2
      - joint_3

  fake_gripper_controller:
    type: "fake"
    joints:
      - joint_4
      - joint_5_mimic