controller_manager:
  ros__parameters:
    update_rate: 10
    use_sim_time: true

    fake_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    fake_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fake_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

    command_interfaces: 
      - position
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

fake_gripper_controller:
  ros__parameters:
    joints:
      - joint_4

    command_interfaces: 
      - position
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
